--- # Configure docker on host machines
- hosts: all
  become: true
  become_user: ansible
  tasks:
    - name: Install packages on hosts
      package: name={{item}} state=present
      loop:
        - docker
        - tree
    - name: Start docker service
      service: name=docker state=started
